name: Build and Deploy Documentation

on:
  push:
    branches:
      - main
      - next
      - vue2

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - run: yarn install
      - run: yarn build
      - run: |
          cd demo
          yarn install
          yarn build-all
      - run: |
          cd docs
          yarn install
      - run: yarn build-docs

      - name: Deploy
        if: github.ref == 'refs/heads/main'
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages
          folder: docs/src/.vuepress/dist
          clean-exclude: |
            next
            vue2

      - name: Deploy next
        if: github.ref == 'refs/heads/next'
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages
          folder: docs/src/.vuepress/dist
          target-folder: ./next

      - name: Deploy vue2
        if: github.ref == 'refs/heads/vue2'
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages
          folder: docs/src/.vuepress/dist
          target-folder: ./vue2