name: Build and Deploy Documentation

on:
  push:
    branches:
      - main
      - next

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14'

      - run: yarn install
      - run: yarn build

      - name: Deploy
        if: github.ref == 'refs/heads/main'
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages
          folder: docs/src/.vuepress/dist

      - name: Deploy next
        if: github.ref == 'refs/heads/next'
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages
          folder: docs/src/.vuepress/dist
          target-folder: ./next