name: Build and Deploy Documentation

on:
  push:
    branches:
      - main
      - next
      - vue2
      - beta

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build packages
        run: npm run build

      - name: Build demo
        run: |
          cd demo
          npm install
          npm run build-all

      - name: Build vuepress
        run: |
          cd docs
          npm install
          npm run build-docs

      - name: Build Typedoc
        run: npm run typedoc

      - name: Deploy main
        if: github.ref == 'refs/heads/main'
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages
          folder: docs/src/.vuepress/dist
          clean-exclude: |
            next
            vue2
            beta

      - name: Deploy next
        if: github.ref == 'refs/heads/next'
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages
          folder: docs/src/.vuepress/dist
          target-folder: ./next

      - name: Deploy vue2
        if: github.ref == 'refs/heads/vue2'
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages
          folder: docs/src/.vuepress/dist
          target-folder: ./vue2

      - name: Deploy beta
        if: github.ref == 'refs/heads/beta'
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages
          folder: docs/src/.vuepress/dist
          target-folder: ./beta

      - name: Deploy Typedoc
        if: github.ref == 'refs/heads/main'
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages
          folder: typedoc
          target-folder: ./typedoc